language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

install:
  - pip install -r requirements.txt
  - if [ "$TRAVIS_PYTHON_VERSION" == "3.2" ]; then travis_retry pip install coverage==3.7.1; fi
  - if [ "$TRAVIS_PYTHON_VERSION" != "3.2" ]; then travis_retry pip install coverage; fi
script:
  coverage run --source=CodeFlow setup.py test

after_success:
  coveralls